// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p_enum.proto

package com.wjybxx.fastjgame.protobuffer;

public final class p_enum {
  private p_enum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code fastjgame.RoleType}
   */
  public enum RoleType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * protoBuf3开始，枚举必须0开始，但是0打出不来信息
     * </pre>
     *
     * <code>ROLE_TYPE_INVALID = 0;</code>
     */
    ROLE_TYPE_INVALID(0),
    /**
     * <pre>
     * 程序
     * </pre>
     *
     * <code>ROLE_TYPE_CODER = 1;</code>
     */
    ROLE_TYPE_CODER(1),
    /**
     * <pre>
     * 策划
     * </pre>
     *
     * <code>ROLE_TYPE_DESIGNERS = 2;</code>
     */
    ROLE_TYPE_DESIGNERS(2),
    /**
     * <pre>
     * 美术
     * </pre>
     *
     * <code>ROLE_TYPE_ARTISTS = 3;</code>
     */
    ROLE_TYPE_ARTISTS(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * protoBuf3开始，枚举必须0开始，但是0打出不来信息
     * </pre>
     *
     * <code>ROLE_TYPE_INVALID = 0;</code>
     */
    public static final int ROLE_TYPE_INVALID_VALUE = 0;
    /**
     * <pre>
     * 程序
     * </pre>
     *
     * <code>ROLE_TYPE_CODER = 1;</code>
     */
    public static final int ROLE_TYPE_CODER_VALUE = 1;
    /**
     * <pre>
     * 策划
     * </pre>
     *
     * <code>ROLE_TYPE_DESIGNERS = 2;</code>
     */
    public static final int ROLE_TYPE_DESIGNERS_VALUE = 2;
    /**
     * <pre>
     * 美术
     * </pre>
     *
     * <code>ROLE_TYPE_ARTISTS = 3;</code>
     */
    public static final int ROLE_TYPE_ARTISTS_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RoleType valueOf(int value) {
      return forNumber(value);
    }

    public static RoleType forNumber(int value) {
      switch (value) {
        case 0: return ROLE_TYPE_INVALID;
        case 1: return ROLE_TYPE_CODER;
        case 2: return ROLE_TYPE_DESIGNERS;
        case 3: return ROLE_TYPE_ARTISTS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RoleType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RoleType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RoleType>() {
            public RoleType findValueByNumber(int number) {
              return RoleType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.wjybxx.fastjgame.protobuffer.p_enum.getDescriptor().getEnumTypes().get(0);
    }

    private static final RoleType[] VALUES = values();

    public static RoleType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RoleType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:fastjgame.RoleType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014p_enum.proto\022\tfastjgame*f\n\010RoleType\022\025\n" +
      "\021ROLE_TYPE_INVALID\020\000\022\023\n\017ROLE_TYPE_CODER\020" +
      "\001\022\027\n\023ROLE_TYPE_DESIGNERS\020\002\022\025\n\021ROLE_TYPE_" +
      "ARTISTS\020\003B,\n com.wjybxx.fastjgame.protob" +
      "ufferB\006p_enumH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
