// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p_game_scene.proto

package com.wjybxx.fastjgame.protobuffer;

public final class p_game_scene {
  private p_game_scene() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fastjgame.Hello)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.fastjgame.RoleType roleTye = 1;</code>
     */
    int getRoleTyeValue();
    /**
     * <code>.fastjgame.RoleType roleTye = 1;</code>
     */
    com.wjybxx.fastjgame.protobuffer.p_enum.RoleType getRoleTye();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * <pre>
   * 消息的命名格式由团队习惯决定
   * </pre>
   *
   * Protobuf type {@code fastjgame.Hello}
   */
  public  static final class Hello extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fastjgame.Hello)
      HelloOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hello.newBuilder() to construct.
    private Hello(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hello() {
      roleTye_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Hello(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              roleTye_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjybxx.fastjgame.protobuffer.p_game_scene.internal_static_fastjgame_Hello_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjybxx.fastjgame.protobuffer.p_game_scene.internal_static_fastjgame_Hello_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello.class, com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello.Builder.class);
    }

    public static final int ROLETYE_FIELD_NUMBER = 1;
    private int roleTye_;
    /**
     * <code>.fastjgame.RoleType roleTye = 1;</code>
     */
    public int getRoleTyeValue() {
      return roleTye_;
    }
    /**
     * <code>.fastjgame.RoleType roleTye = 1;</code>
     */
    public com.wjybxx.fastjgame.protobuffer.p_enum.RoleType getRoleTye() {
      com.wjybxx.fastjgame.protobuffer.p_enum.RoleType result = com.wjybxx.fastjgame.protobuffer.p_enum.RoleType.valueOf(roleTye_);
      return result == null ? com.wjybxx.fastjgame.protobuffer.p_enum.RoleType.UNRECOGNIZED : result;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (roleTye_ != com.wjybxx.fastjgame.protobuffer.p_enum.RoleType.ROLE_TYPE_INVALID.getNumber()) {
        output.writeEnum(1, roleTye_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (roleTye_ != com.wjybxx.fastjgame.protobuffer.p_enum.RoleType.ROLE_TYPE_INVALID.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, roleTye_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello)) {
        return super.equals(obj);
      }
      com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello other = (com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello) obj;

      boolean result = true;
      result = result && roleTye_ == other.roleTye_;
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROLETYE_FIELD_NUMBER;
      hash = (53 * hash) + roleTye_;
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 消息的命名格式由团队习惯决定
     * </pre>
     *
     * Protobuf type {@code fastjgame.Hello}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fastjgame.Hello)
        com.wjybxx.fastjgame.protobuffer.p_game_scene.HelloOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjybxx.fastjgame.protobuffer.p_game_scene.internal_static_fastjgame_Hello_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjybxx.fastjgame.protobuffer.p_game_scene.internal_static_fastjgame_Hello_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello.class, com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello.Builder.class);
      }

      // Construct using com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        roleTye_ = 0;

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjybxx.fastjgame.protobuffer.p_game_scene.internal_static_fastjgame_Hello_descriptor;
      }

      public com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello getDefaultInstanceForType() {
        return com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello.getDefaultInstance();
      }

      public com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello build() {
        com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello buildPartial() {
        com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello result = new com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello(this);
        result.roleTye_ = roleTye_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello) {
          return mergeFrom((com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello other) {
        if (other == com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello.getDefaultInstance()) return this;
        if (other.roleTye_ != 0) {
          setRoleTyeValue(other.getRoleTyeValue());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int roleTye_ = 0;
      /**
       * <code>.fastjgame.RoleType roleTye = 1;</code>
       */
      public int getRoleTyeValue() {
        return roleTye_;
      }
      /**
       * <code>.fastjgame.RoleType roleTye = 1;</code>
       */
      public Builder setRoleTyeValue(int value) {
        roleTye_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.fastjgame.RoleType roleTye = 1;</code>
       */
      public com.wjybxx.fastjgame.protobuffer.p_enum.RoleType getRoleTye() {
        com.wjybxx.fastjgame.protobuffer.p_enum.RoleType result = com.wjybxx.fastjgame.protobuffer.p_enum.RoleType.valueOf(roleTye_);
        return result == null ? com.wjybxx.fastjgame.protobuffer.p_enum.RoleType.UNRECOGNIZED : result;
      }
      /**
       * <code>.fastjgame.RoleType roleTye = 1;</code>
       */
      public Builder setRoleTye(com.wjybxx.fastjgame.protobuffer.p_enum.RoleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        roleTye_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.fastjgame.RoleType roleTye = 1;</code>
       */
      public Builder clearRoleTye() {
        
        roleTye_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fastjgame.Hello)
    }

    // @@protoc_insertion_point(class_scope:fastjgame.Hello)
    private static final com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello();
    }

    public static com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Hello>
        PARSER = new com.google.protobuf.AbstractParser<Hello>() {
      public Hello parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hello(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hello> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hello> getParserForType() {
      return PARSER;
    }

    public com.wjybxx.fastjgame.protobuffer.p_game_scene.Hello getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fastjgame_Hello_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fastjgame_Hello_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022p_game_scene.proto\022\tfastjgame\032\014p_enum." +
      "proto\032\016p_struct.proto\";\n\005Hello\022$\n\007roleTy" +
      "e\030\001 \001(\0162\023.fastjgame.RoleType\022\014\n\004name\030\002 \001" +
      "(\tB2\n com.wjybxx.fastjgame.protobufferB\014" +
      "p_game_sceneH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wjybxx.fastjgame.protobuffer.p_enum.getDescriptor(),
          com.wjybxx.fastjgame.protobuffer.p_struct.getDescriptor(),
        }, assigner);
    internal_static_fastjgame_Hello_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fastjgame_Hello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fastjgame_Hello_descriptor,
        new java.lang.String[] { "RoleTye", "Name", });
    com.wjybxx.fastjgame.protobuffer.p_enum.getDescriptor();
    com.wjybxx.fastjgame.protobuffer.p_struct.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
