// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p_sync_center_warzone.proto

package com.wjybxx.fastjgame.protobuffer;

public final class p_sync_center_warzone {
  private p_sync_center_warzone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033p_sync_center_warzone.proto\022\tfastjgame" +
      "\032\014p_enum.proto\032\016p_struct.protoB;\n com.wj" +
      "ybxx.fastjgame.protobufferB\025p_sync_cente" +
      "r_warzoneH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wjybxx.fastjgame.protobuffer.p_enum.getDescriptor(),
          com.wjybxx.fastjgame.protobuffer.p_struct.getDescriptor(),
        }, assigner);
    com.wjybxx.fastjgame.protobuffer.p_enum.getDescriptor();
    com.wjybxx.fastjgame.protobuffer.p_struct.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
