// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p_sync_center_scene.proto

package com.wjybxx.fastjgame.protobuffer;

public final class p_sync_center_scene {
  private p_sync_center_scene() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface p_center_command_single_scene_startOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fastjgame.p_center_command_single_scene_start)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 命令scene启动以下互斥区域
     * </pre>
     *
     * <code>repeated int32 activeMutexRegions = 1;</code>
     */
    java.util.List<java.lang.Integer> getActiveMutexRegionsList();
    /**
     * <pre>
     * 命令scene启动以下互斥区域
     * </pre>
     *
     * <code>repeated int32 activeMutexRegions = 1;</code>
     */
    int getActiveMutexRegionsCount();
    /**
     * <pre>
     * 命令scene启动以下互斥区域
     * </pre>
     *
     * <code>repeated int32 activeMutexRegions = 1;</code>
     */
    int getActiveMutexRegions(int index);
  }
  /**
   * <pre>
   * center同意scene启动，并启动以下互斥区域
   * </pre>
   *
   * Protobuf type {@code fastjgame.p_center_command_single_scene_start}
   */
  public  static final class p_center_command_single_scene_start extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fastjgame.p_center_command_single_scene_start)
      p_center_command_single_scene_startOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use p_center_command_single_scene_start.newBuilder() to construct.
    private p_center_command_single_scene_start(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private p_center_command_single_scene_start() {
      activeMutexRegions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private p_center_command_single_scene_start(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                activeMutexRegions_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              activeMutexRegions_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                activeMutexRegions_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                activeMutexRegions_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          activeMutexRegions_ = java.util.Collections.unmodifiableList(activeMutexRegions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_start_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_start_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start.class, com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start.Builder.class);
    }

    public static final int ACTIVEMUTEXREGIONS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> activeMutexRegions_;
    /**
     * <pre>
     * 命令scene启动以下互斥区域
     * </pre>
     *
     * <code>repeated int32 activeMutexRegions = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getActiveMutexRegionsList() {
      return activeMutexRegions_;
    }
    /**
     * <pre>
     * 命令scene启动以下互斥区域
     * </pre>
     *
     * <code>repeated int32 activeMutexRegions = 1;</code>
     */
    public int getActiveMutexRegionsCount() {
      return activeMutexRegions_.size();
    }
    /**
     * <pre>
     * 命令scene启动以下互斥区域
     * </pre>
     *
     * <code>repeated int32 activeMutexRegions = 1;</code>
     */
    public int getActiveMutexRegions(int index) {
      return activeMutexRegions_.get(index);
    }
    private int activeMutexRegionsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getActiveMutexRegionsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(activeMutexRegionsMemoizedSerializedSize);
      }
      for (int i = 0; i < activeMutexRegions_.size(); i++) {
        output.writeInt32NoTag(activeMutexRegions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < activeMutexRegions_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(activeMutexRegions_.get(i));
        }
        size += dataSize;
        if (!getActiveMutexRegionsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        activeMutexRegionsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start)) {
        return super.equals(obj);
      }
      com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start other = (com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start) obj;

      boolean result = true;
      result = result && getActiveMutexRegionsList()
          .equals(other.getActiveMutexRegionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getActiveMutexRegionsCount() > 0) {
        hash = (37 * hash) + ACTIVEMUTEXREGIONS_FIELD_NUMBER;
        hash = (53 * hash) + getActiveMutexRegionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * center同意scene启动，并启动以下互斥区域
     * </pre>
     *
     * Protobuf type {@code fastjgame.p_center_command_single_scene_start}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fastjgame.p_center_command_single_scene_start)
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_startOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_start_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_start_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start.class, com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start.Builder.class);
      }

      // Construct using com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        activeMutexRegions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_start_descriptor;
      }

      public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start getDefaultInstanceForType() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start.getDefaultInstance();
      }

      public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start build() {
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start buildPartial() {
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start result = new com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          activeMutexRegions_ = java.util.Collections.unmodifiableList(activeMutexRegions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.activeMutexRegions_ = activeMutexRegions_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start) {
          return mergeFrom((com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start other) {
        if (other == com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start.getDefaultInstance()) return this;
        if (!other.activeMutexRegions_.isEmpty()) {
          if (activeMutexRegions_.isEmpty()) {
            activeMutexRegions_ = other.activeMutexRegions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureActiveMutexRegionsIsMutable();
            activeMutexRegions_.addAll(other.activeMutexRegions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> activeMutexRegions_ = java.util.Collections.emptyList();
      private void ensureActiveMutexRegionsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          activeMutexRegions_ = new java.util.ArrayList<java.lang.Integer>(activeMutexRegions_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 命令scene启动以下互斥区域
       * </pre>
       *
       * <code>repeated int32 activeMutexRegions = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getActiveMutexRegionsList() {
        return java.util.Collections.unmodifiableList(activeMutexRegions_);
      }
      /**
       * <pre>
       * 命令scene启动以下互斥区域
       * </pre>
       *
       * <code>repeated int32 activeMutexRegions = 1;</code>
       */
      public int getActiveMutexRegionsCount() {
        return activeMutexRegions_.size();
      }
      /**
       * <pre>
       * 命令scene启动以下互斥区域
       * </pre>
       *
       * <code>repeated int32 activeMutexRegions = 1;</code>
       */
      public int getActiveMutexRegions(int index) {
        return activeMutexRegions_.get(index);
      }
      /**
       * <pre>
       * 命令scene启动以下互斥区域
       * </pre>
       *
       * <code>repeated int32 activeMutexRegions = 1;</code>
       */
      public Builder setActiveMutexRegions(
          int index, int value) {
        ensureActiveMutexRegionsIsMutable();
        activeMutexRegions_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 命令scene启动以下互斥区域
       * </pre>
       *
       * <code>repeated int32 activeMutexRegions = 1;</code>
       */
      public Builder addActiveMutexRegions(int value) {
        ensureActiveMutexRegionsIsMutable();
        activeMutexRegions_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 命令scene启动以下互斥区域
       * </pre>
       *
       * <code>repeated int32 activeMutexRegions = 1;</code>
       */
      public Builder addAllActiveMutexRegions(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureActiveMutexRegionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, activeMutexRegions_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 命令scene启动以下互斥区域
       * </pre>
       *
       * <code>repeated int32 activeMutexRegions = 1;</code>
       */
      public Builder clearActiveMutexRegions() {
        activeMutexRegions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fastjgame.p_center_command_single_scene_start)
    }

    // @@protoc_insertion_point(class_scope:fastjgame.p_center_command_single_scene_start)
    private static final com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start();
    }

    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<p_center_command_single_scene_start>
        PARSER = new com.google.protobuf.AbstractParser<p_center_command_single_scene_start>() {
      public p_center_command_single_scene_start parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new p_center_command_single_scene_start(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<p_center_command_single_scene_start> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<p_center_command_single_scene_start> getParserForType() {
      return PARSER;
    }

    public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface p_center_command_single_scene_start_resultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fastjgame.p_center_command_single_scene_start_result)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 上一条信息的响应，表示成功启动了对应的区域
   * </pre>
   *
   * Protobuf type {@code fastjgame.p_center_command_single_scene_start_result}
   */
  public  static final class p_center_command_single_scene_start_result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fastjgame.p_center_command_single_scene_start_result)
      p_center_command_single_scene_start_resultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use p_center_command_single_scene_start_result.newBuilder() to construct.
    private p_center_command_single_scene_start_result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private p_center_command_single_scene_start_result() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private p_center_command_single_scene_start_result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_start_result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_start_result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result.class, com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result)) {
        return super.equals(obj);
      }
      com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result other = (com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 上一条信息的响应，表示成功启动了对应的区域
     * </pre>
     *
     * Protobuf type {@code fastjgame.p_center_command_single_scene_start_result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fastjgame.p_center_command_single_scene_start_result)
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_resultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_start_result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_start_result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result.class, com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result.Builder.class);
      }

      // Construct using com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_start_result_descriptor;
      }

      public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result getDefaultInstanceForType() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result.getDefaultInstance();
      }

      public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result build() {
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result buildPartial() {
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result result = new com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result) {
          return mergeFrom((com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result other) {
        if (other == com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fastjgame.p_center_command_single_scene_start_result)
    }

    // @@protoc_insertion_point(class_scope:fastjgame.p_center_command_single_scene_start_result)
    private static final com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result();
    }

    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<p_center_command_single_scene_start_result>
        PARSER = new com.google.protobuf.AbstractParser<p_center_command_single_scene_start_result>() {
      public p_center_command_single_scene_start_result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new p_center_command_single_scene_start_result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<p_center_command_single_scene_start_result> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<p_center_command_single_scene_start_result> getParserForType() {
      return PARSER;
    }

    public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_start_result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface p_center_command_single_scene_active_regionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fastjgame.p_center_command_single_scene_active_regions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 让当前进程启动的区域
     * </pre>
     *
     * <code>repeated int32 activeRegions = 2;</code>
     */
    java.util.List<java.lang.Integer> getActiveRegionsList();
    /**
     * <pre>
     * 让当前进程启动的区域
     * </pre>
     *
     * <code>repeated int32 activeRegions = 2;</code>
     */
    int getActiveRegionsCount();
    /**
     * <pre>
     * 让当前进程启动的区域
     * </pre>
     *
     * <code>repeated int32 activeRegions = 2;</code>
     */
    int getActiveRegions(int index);
  }
  /**
   * <pre>
   * center服让scene服启动以下区域，用在宕机处理时。
   * </pre>
   *
   * Protobuf type {@code fastjgame.p_center_command_single_scene_active_regions}
   */
  public  static final class p_center_command_single_scene_active_regions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fastjgame.p_center_command_single_scene_active_regions)
      p_center_command_single_scene_active_regionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use p_center_command_single_scene_active_regions.newBuilder() to construct.
    private p_center_command_single_scene_active_regions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private p_center_command_single_scene_active_regions() {
      activeRegions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private p_center_command_single_scene_active_regions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                activeRegions_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              activeRegions_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                activeRegions_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                activeRegions_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          activeRegions_ = java.util.Collections.unmodifiableList(activeRegions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_active_regions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_active_regions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions.class, com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions.Builder.class);
    }

    public static final int ACTIVEREGIONS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> activeRegions_;
    /**
     * <pre>
     * 让当前进程启动的区域
     * </pre>
     *
     * <code>repeated int32 activeRegions = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getActiveRegionsList() {
      return activeRegions_;
    }
    /**
     * <pre>
     * 让当前进程启动的区域
     * </pre>
     *
     * <code>repeated int32 activeRegions = 2;</code>
     */
    public int getActiveRegionsCount() {
      return activeRegions_.size();
    }
    /**
     * <pre>
     * 让当前进程启动的区域
     * </pre>
     *
     * <code>repeated int32 activeRegions = 2;</code>
     */
    public int getActiveRegions(int index) {
      return activeRegions_.get(index);
    }
    private int activeRegionsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getActiveRegionsList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(activeRegionsMemoizedSerializedSize);
      }
      for (int i = 0; i < activeRegions_.size(); i++) {
        output.writeInt32NoTag(activeRegions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < activeRegions_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(activeRegions_.get(i));
        }
        size += dataSize;
        if (!getActiveRegionsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        activeRegionsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions)) {
        return super.equals(obj);
      }
      com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions other = (com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions) obj;

      boolean result = true;
      result = result && getActiveRegionsList()
          .equals(other.getActiveRegionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getActiveRegionsCount() > 0) {
        hash = (37 * hash) + ACTIVEREGIONS_FIELD_NUMBER;
        hash = (53 * hash) + getActiveRegionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * center服让scene服启动以下区域，用在宕机处理时。
     * </pre>
     *
     * Protobuf type {@code fastjgame.p_center_command_single_scene_active_regions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fastjgame.p_center_command_single_scene_active_regions)
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_active_regions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_active_regions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions.class, com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions.Builder.class);
      }

      // Construct using com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        activeRegions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_active_regions_descriptor;
      }

      public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions getDefaultInstanceForType() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions.getDefaultInstance();
      }

      public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions build() {
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions buildPartial() {
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions result = new com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          activeRegions_ = java.util.Collections.unmodifiableList(activeRegions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.activeRegions_ = activeRegions_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions) {
          return mergeFrom((com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions other) {
        if (other == com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions.getDefaultInstance()) return this;
        if (!other.activeRegions_.isEmpty()) {
          if (activeRegions_.isEmpty()) {
            activeRegions_ = other.activeRegions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureActiveRegionsIsMutable();
            activeRegions_.addAll(other.activeRegions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> activeRegions_ = java.util.Collections.emptyList();
      private void ensureActiveRegionsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          activeRegions_ = new java.util.ArrayList<java.lang.Integer>(activeRegions_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 让当前进程启动的区域
       * </pre>
       *
       * <code>repeated int32 activeRegions = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getActiveRegionsList() {
        return java.util.Collections.unmodifiableList(activeRegions_);
      }
      /**
       * <pre>
       * 让当前进程启动的区域
       * </pre>
       *
       * <code>repeated int32 activeRegions = 2;</code>
       */
      public int getActiveRegionsCount() {
        return activeRegions_.size();
      }
      /**
       * <pre>
       * 让当前进程启动的区域
       * </pre>
       *
       * <code>repeated int32 activeRegions = 2;</code>
       */
      public int getActiveRegions(int index) {
        return activeRegions_.get(index);
      }
      /**
       * <pre>
       * 让当前进程启动的区域
       * </pre>
       *
       * <code>repeated int32 activeRegions = 2;</code>
       */
      public Builder setActiveRegions(
          int index, int value) {
        ensureActiveRegionsIsMutable();
        activeRegions_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 让当前进程启动的区域
       * </pre>
       *
       * <code>repeated int32 activeRegions = 2;</code>
       */
      public Builder addActiveRegions(int value) {
        ensureActiveRegionsIsMutable();
        activeRegions_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 让当前进程启动的区域
       * </pre>
       *
       * <code>repeated int32 activeRegions = 2;</code>
       */
      public Builder addAllActiveRegions(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureActiveRegionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, activeRegions_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 让当前进程启动的区域
       * </pre>
       *
       * <code>repeated int32 activeRegions = 2;</code>
       */
      public Builder clearActiveRegions() {
        activeRegions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fastjgame.p_center_command_single_scene_active_regions)
    }

    // @@protoc_insertion_point(class_scope:fastjgame.p_center_command_single_scene_active_regions)
    private static final com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions();
    }

    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<p_center_command_single_scene_active_regions>
        PARSER = new com.google.protobuf.AbstractParser<p_center_command_single_scene_active_regions>() {
      public p_center_command_single_scene_active_regions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new p_center_command_single_scene_active_regions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<p_center_command_single_scene_active_regions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<p_center_command_single_scene_active_regions> getParserForType() {
      return PARSER;
    }

    public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface p_center_command_single_scene_active_regions_resultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fastjgame.p_center_command_single_scene_active_regions_result)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 表示scene已处理center发来的启动区域请求
   * </pre>
   *
   * Protobuf type {@code fastjgame.p_center_command_single_scene_active_regions_result}
   */
  public  static final class p_center_command_single_scene_active_regions_result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fastjgame.p_center_command_single_scene_active_regions_result)
      p_center_command_single_scene_active_regions_resultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use p_center_command_single_scene_active_regions_result.newBuilder() to construct.
    private p_center_command_single_scene_active_regions_result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private p_center_command_single_scene_active_regions_result() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private p_center_command_single_scene_active_regions_result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_active_regions_result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_active_regions_result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result.class, com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result)) {
        return super.equals(obj);
      }
      com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result other = (com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 表示scene已处理center发来的启动区域请求
     * </pre>
     *
     * Protobuf type {@code fastjgame.p_center_command_single_scene_active_regions_result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fastjgame.p_center_command_single_scene_active_regions_result)
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_resultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_active_regions_result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_active_regions_result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result.class, com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result.Builder.class);
      }

      // Construct using com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.internal_static_fastjgame_p_center_command_single_scene_active_regions_result_descriptor;
      }

      public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result getDefaultInstanceForType() {
        return com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result.getDefaultInstance();
      }

      public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result build() {
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result buildPartial() {
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result result = new com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result) {
          return mergeFrom((com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result other) {
        if (other == com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fastjgame.p_center_command_single_scene_active_regions_result)
    }

    // @@protoc_insertion_point(class_scope:fastjgame.p_center_command_single_scene_active_regions_result)
    private static final com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result();
    }

    public static com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<p_center_command_single_scene_active_regions_result>
        PARSER = new com.google.protobuf.AbstractParser<p_center_command_single_scene_active_regions_result>() {
      public p_center_command_single_scene_active_regions_result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new p_center_command_single_scene_active_regions_result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<p_center_command_single_scene_active_regions_result> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<p_center_command_single_scene_active_regions_result> getParserForType() {
      return PARSER;
    }

    public com.wjybxx.fastjgame.protobuffer.p_sync_center_scene.p_center_command_single_scene_active_regions_result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fastjgame_p_center_command_single_scene_start_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fastjgame_p_center_command_single_scene_start_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fastjgame_p_center_command_single_scene_start_result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fastjgame_p_center_command_single_scene_start_result_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fastjgame_p_center_command_single_scene_active_regions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fastjgame_p_center_command_single_scene_active_regions_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fastjgame_p_center_command_single_scene_active_regions_result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fastjgame_p_center_command_single_scene_active_regions_result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031p_sync_center_scene.proto\022\tfastjgame\032\014" +
      "p_enum.proto\032\016p_struct.proto\"A\n#p_center" +
      "_command_single_scene_start\022\032\n\022activeMut" +
      "exRegions\030\001 \003(\005\",\n*p_center_command_sing" +
      "le_scene_start_result\"E\n,p_center_comman" +
      "d_single_scene_active_regions\022\025\n\ractiveR" +
      "egions\030\002 \003(\005\"5\n3p_center_command_single_" +
      "scene_active_regions_resultB9\n com.wjybx" +
      "x.fastjgame.protobufferB\023p_sync_center_s" +
      "ceneH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wjybxx.fastjgame.protobuffer.p_enum.getDescriptor(),
          com.wjybxx.fastjgame.protobuffer.p_struct.getDescriptor(),
        }, assigner);
    internal_static_fastjgame_p_center_command_single_scene_start_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fastjgame_p_center_command_single_scene_start_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fastjgame_p_center_command_single_scene_start_descriptor,
        new java.lang.String[] { "ActiveMutexRegions", });
    internal_static_fastjgame_p_center_command_single_scene_start_result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fastjgame_p_center_command_single_scene_start_result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fastjgame_p_center_command_single_scene_start_result_descriptor,
        new java.lang.String[] { });
    internal_static_fastjgame_p_center_command_single_scene_active_regions_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_fastjgame_p_center_command_single_scene_active_regions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fastjgame_p_center_command_single_scene_active_regions_descriptor,
        new java.lang.String[] { "ActiveRegions", });
    internal_static_fastjgame_p_center_command_single_scene_active_regions_result_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_fastjgame_p_center_command_single_scene_active_regions_result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fastjgame_p_center_command_single_scene_active_regions_result_descriptor,
        new java.lang.String[] { });
    com.wjybxx.fastjgame.protobuffer.p_enum.getDescriptor();
    com.wjybxx.fastjgame.protobuffer.p_struct.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
