// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p_warzone_game.proto

package com.wjybxx.fastjgame.protobuffer;

public final class p_warzone_game {
  private p_warzone_game() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024p_warzone_game.proto\022\tfastjgame\032\014p_enu" +
      "m.proto\032\016p_struct.protoB4\n com.wjybxx.fa" +
      "stjgame.protobufferB\016p_warzone_gameH\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wjybxx.fastjgame.protobuffer.p_enum.getDescriptor(),
          com.wjybxx.fastjgame.protobuffer.p_struct.getDescriptor(),
        }, assigner);
    com.wjybxx.fastjgame.protobuffer.p_enum.getDescriptor();
    com.wjybxx.fastjgame.protobuffer.p_struct.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
